package org.acme.movimientos.controllers.movimientosController;

import jakarta.inject.Inject;
import jakarta.validation.constraints.NotNull;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.*;

import org.acme.movimientos.dtos.MovimientosDto;
import org.acme.movimientos.services.CuentaService;
import org.acme.movimientos.utilities.TokenUtility;

import java.util.ArrayList;
import java.util.List;


import java.util.logging.Logger;


@Path("/efectivo/movimientos/{cuenta}/{fecha}/{cep}/{operationType}")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class MovimientosController {

    private static final Logger LOG = Logger.getLogger(MovimientosController.class.getName());
    
    @Inject
    CuentaService cuentaService;


    
    @GET
    @Path("")
    public Response getMovimientosV2(@PathParam("cuenta") @NotNull String cuenta, @PathParam("fecha") @NotNull String fecha,@PathParam("cep") @NotNull String cep,@PathParam("operationType") @NotNull String operationType, @HeaderParam("Authorization") String authorizationHeader) {
        String response=null;
        try {
            // Validar que los parámetros no sean nulos o vacíos
            if (cuenta == null || cuenta.isEmpty()  || cuenta.isBlank() || fecha == null || fecha.isEmpty() || fecha.isBlank()
            		|| cep == null || cep.isEmpty() || cep.isBlank()
            		|| operationType == null || operationType.isEmpty() || operationType.isBlank()
            		) {
                LOG.severe("Los parámetros cuenta, fecha, cep o operationType son requeridos");
                return Response.status(Response.Status.BAD_REQUEST).entity("Los parámetros cuenta, fecha, cep o operationType son requeridos").build();
            }

            // Verificar si el encabezado de autorización es nulo o está vacío
            if (authorizationHeader == null || authorizationHeader.isEmpty()) {
                LOG.severe("Se requiere el encabezado de autorización");
                return Response.status(Response.Status.BAD_REQUEST).entity("Se requiere el encabezado de autorización").build();
            }else{
                LOG.info("El encabezado de autrizacion es: "+authorizationHeader);
            }

            // Verificar y obtener el "cui" del JWT
            String cui = "123456";//TokenUtility.verifyAndGetCui(authorizationHeader);
            LOG.info("CUI: "+cui);
            // Verificar y obtener el "cui" del JWT
            String folio = "1234";//TokenUtility.verifyAndGetFolio(authorizationHeader);
            LOG.info("getMovimientosV2 folio: "+folio);


            //Consumo del EndPoint del sp

            String numerocuenta = "1510100344327";//cuentaService.obtenerNumeroCuenta(cuenta,cui,folio);//SP ConsultaCuentasPorCUI
            LOG.info("getMovimientosV2 numerocuenta: "+numerocuenta);//quitar en produccion
            if (numerocuenta == null) {
                LOG.severe("No se pudo obtener el numero de cuenta... cuentaService.obtenerNumeroCuenta");
                return Response.status(Response.Status.INTERNAL_SERVER_ERROR).entity("No se pudo obtener el numero de cuenta").build();
            }

            //EndPoint que trae los datos
            /*response = cuentaService.obtenerMovimientosDesdeEndpoint(numerocuenta, fecha);

            // Convertir la respuesta JSON a una lista de objetos MovimientosDto
            ObjectMapper objectMapper = new ObjectMapper();

            //Descomentar para dejar de mockear y comentar el mockeo de respuesta
            Responses resp = objectMapper.readValue(response, new TypeReference<Responses>() {});
            List<AccountTransactions> AccountTransactionsList = resp.getCanonicalInvexMessage().getBody().getAccountTransactionsRes().getAccountTransactions();
            List<MovimientosDto> resultList =  new ArrayList<>();
            MovimientosList resFinal = new MovimientosList();
            for (AccountTransactions accountTransactions:AccountTransactionsList ){
                MovimientosDto result = new MovimientosDto();
                result.setMovimiento(accountTransactions.getOperationAmount());
                result.setConcepto(accountTransactions.getConcept());
                result.setFecha(accountTransactions.getOperationDate());
                result.setSaldo(accountTransactions.getBalance());
                resultList.add(result);
            }
            resFinal.setMovimientos(resultList);
            return Response.ok(resFinal).build();
            */
            
            //Mockeo respuesta
            List<MovimientosDto> movimientosList = new ArrayList<>();
            if(cuenta.equals("1")) {
            	
            	return Response.ok("{\n"
            			+ "  \"transactionID\": \"57a318d4-1b23-41fa-baac-c01630ba2849\",\n"
            			+ "  \"httpStatus\": 200,\n"
            			+ "  \"timestamp\": \"2023-07-28T15:26:47.885759\",\n"
            			+ "  \"message\": \"Microservice working fine\",\n"
                		+ "  \"token\": \"" + authorizationHeader + "\"," 
            			+ "  \"data\": {\n"
            			+ "    \"movimientos\": [\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"PAGO 4 JUAN JOSE AGUILAR\",\n"
            			+ "        \"fecha\": \"2023-06-01T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"2396.94\",\n"
            			+ "        \"saldo\": \"177370.85\",\n"
            			+ "        \"referencia\": \"7528300\",\n"
            			+ "        \"fechaAceptacion\": \"2023-06-01T00:31:03-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-06-01T00:31:04-05:00\",\n"
            			+ "        \"emisor\": \"SANTANDER\",\n"
            			+ "        \"cuentaOrdenante\": \"014180605605294205\",\n"
            			+ "        \"nombreOrdenante\": \"JUANJOSEAGUILARRIVERA\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023060140014TRAP0000431254700\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"pago prestamo \",\n"
            			+ "        \"fecha\": \"2023-05-31T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"1300\",\n"
            			+ "        \"saldo\": \"163404.31\",\n"
            			+ "        \"referencia\": \"4092351\",\n"
            			+ "        \"fechaAceptacion\": \"2023-05-31T15:46:45-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-05-31T15:46:45-05:00\",\n"
            			+ "        \"emisor\": \"STP\",\n"
            			+ "        \"cuentaOrdenante\": \"646013206858315561\",\n"
            			+ "        \"nombreOrdenante\": \"JORGEALEJANDROGOMORACARMONA\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"CPO58796137714\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Compra de equipo de oficina\",\n"
            			+ "        \"fecha\": \"2023-07-20T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"5000\",\n"
            			+ "        \"saldo\": \"172404.31\",\n"
            			+ "        \"referencia\": \"2023072001\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-20T10:15:30-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-20T10:15:30-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"348612987530912456\",\n"
            			+ "        \"nombreOrdenante\": \"EMPRESA ABC\",\n"
            			+ "        \"receptor\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"cuentaBeneficiario\": \"014180605605294205\",\n"
            			+ "        \"nombreBeneficiario\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"claveRastreo\": \"2023072001INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de nómina\",\n"
            			+ "        \"fecha\": \"2023-07-15T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"7500.50\",\n"
            			+ "        \"saldo\": \"164903.81\",\n"
            			+ "        \"referencia\": \"2023071502\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-15T08:30:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-15T08:30:00-05:00\",\n"
            			+ "        \"emisor\": \"EMPRESA XYZ\",\n"
            			+ "        \"cuentaOrdenante\": \"998877665544332211\",\n"
            			+ "        \"nombreOrdenante\": \"EMPLEADO 1\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023071502INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Depósito de ventas\",\n"
            			+ "        \"fecha\": \"2023-07-28T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"8500.75\",\n"
            			+ "        \"saldo\": \"173404.56\",\n"
            			+ "        \"referencia\": \"2023072801\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-28T14:10:20-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-28T14:10:21-05:00\",\n"
            			+ "        \"emisor\": \"CLIENTE ABC\",\n"
            			+ "        \"cuentaOrdenante\": \"112233445566778899\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE ABC\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023072801INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de servicios\",\n"
            			+ "        \"fecha\": \"2023-07-05T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"1200.25\",\n"
            			+ "        \"saldo\": \"166204.31\",\n"
            			+ "        \"referencia\": \"2023070501\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-05T12:45:30-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-05T12:45:30-05:00\",\n"
            			+ "        \"emisor\": \"SERVICIOS ABC\",\n"
            			+ "        \"cuentaOrdenante\": \"777788889999000011\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023070501INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de impuestos\",\n"
            			+ "        \"fecha\": \"2023-07-10T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"3500\",\n"
            			+ "        \"saldo\": \"162704.31\",\n"
            			+ "        \"referencia\": \"2023071001\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-10T09:20:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-10T09:20:00-05:00\",\n"
            			+ "        \"emisor\": \"GOBIERNO\",\n"
            			+ "        \"cuentaOrdenante\": \"333322221111444455\",\n"
            			+ "        \"nombreOrdenante\": \"EMPRESA XYZ\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023071001INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Retiro de efectivo\",\n"
            			+ "        \"fecha\": \"2023-07-12T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"-2000\",\n"
            			+ "        \"saldo\": \"160704.31\",\n"
            			+ "        \"referencia\": \"2023071201\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-12T13:55:10-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-12T13:55:11-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"448877112233556677\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"CLIENTE XYZ\",\n"
            			+ "        \"cuentaBeneficiario\": \"014180605605294205\",\n"
            			+ "        \"nombreBeneficiario\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"claveRastreo\": \"2023071201INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Retiro\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Transferencia de fondos\",\n"
            			+ "        \"fecha\": \"2023-07-22T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"-5000.50\",\n"
            			+ "        \"saldo\": \"155703.81\",\n"
            			+ "        \"referencia\": \"2023072201\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-22T11:30:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-22T11:30:00-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"448877112233556677\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"EMPRESA ABC\",\n"
            			+ "        \"cuentaBeneficiario\": \"112233445566778899\",\n"
            			+ "        \"nombreBeneficiario\": \"EMPRESA ABC\",\n"
            			+ "        \"claveRastreo\": \"2023072201INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de factura\",\n"
            			+ "        \"fecha\": \"2023-07-18T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"350.75\",\n"
            			+ "        \"saldo\": \"155353.06\",\n"
            			+ "        \"referencia\": \"2023071801\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-18T09:15:20-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-18T09:15:20-05:00\",\n"
            			+ "        \"emisor\": \"EMPRESA XYZ\",\n"
            			+ "        \"cuentaOrdenante\": \"998877665544332211\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE 2\",\n"
            			+ "        \"receptor\": \"PROVEEDOR ABC\",\n"
            			+ "        \"cuentaBeneficiario\": \"556677889900112233\",\n"
            			+ "        \"nombreBeneficiario\": \"PROVEEDOR ABC\",\n"
            			+ "        \"claveRastreo\": \"2023071801INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      }\n"
            			+ "    ]\n"
            			+ "  }\n"
            			+ "}")
                        .build();
            }else if(cuenta.equals("2")){
            	return Response.ok("{\n"
            			+ "  \"transactionID\": \"57a318d4-1b23-41fa-baac-c01630ba2849\",\n"
            			+ "  \"httpStatus\": 200,\n"
            			+ "  \"timestamp\": \"2023-07-28T15:26:47.885759\",\n"
            			+ "  \"message\": \"Microservice working fine\",\n"
                		+ "  \"token\": \"" + authorizationHeader + "\"," 
            			+ "  \"data\": {\n"
            			+ "    \"movimientos\": [\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"PAGO 4 JUAN JOSE AGUILAR\",\n"
            			+ "        \"fecha\": \"2023-06-01T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"2396.94\",\n"
            			+ "        \"saldo\": \"177370.85\",\n"
            			+ "        \"referencia\": \"7528300\",\n"
            			+ "        \"fechaAceptacion\": \"2023-06-01T00:31:03-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-06-01T00:31:04-05:00\",\n"
            			+ "        \"emisor\": \"SANTANDER\",\n"
            			+ "        \"cuentaOrdenante\": \"014180605605294205\",\n"
            			+ "        \"nombreOrdenante\": \"JUANJOSEAGUILARRIVERA\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023060140014TRAP0000431254700\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"pago prestamo \",\n"
            			+ "        \"fecha\": \"2023-05-31T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"1300\",\n"
            			+ "        \"saldo\": \"163404.31\",\n"
            			+ "        \"referencia\": \"4092351\",\n"
            			+ "        \"fechaAceptacion\": \"2023-05-31T15:46:45-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-05-31T15:46:45-05:00\",\n"
            			+ "        \"emisor\": \"STP\",\n"
            			+ "        \"cuentaOrdenante\": \"646013206858315561\",\n"
            			+ "        \"nombreOrdenante\": \"JORGEALEJANDROGOMORACARMONA\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"CPO58796137714\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Compra de equipo de oficina\",\n"
            			+ "        \"fecha\": \"2023-07-20T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"5000\",\n"
            			+ "        \"saldo\": \"172404.31\",\n"
            			+ "        \"referencia\": \"2023072001\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-20T10:15:30-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-20T10:15:30-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"348612987530912456\",\n"
            			+ "        \"nombreOrdenante\": \"EMPRESA ABC\",\n"
            			+ "        \"receptor\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"cuentaBeneficiario\": \"014180605605294205\",\n"
            			+ "        \"nombreBeneficiario\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"claveRastreo\": \"2023072001INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de nómina\",\n"
            			+ "        \"fecha\": \"2023-07-15T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"7500.50\",\n"
            			+ "        \"saldo\": \"164903.81\",\n"
            			+ "        \"referencia\": \"2023071502\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-15T08:30:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-15T08:30:00-05:00\",\n"
            			+ "        \"emisor\": \"EMPRESA XYZ\",\n"
            			+ "        \"cuentaOrdenante\": \"998877665544332211\",\n"
            			+ "        \"nombreOrdenante\": \"EMPLEADO 1\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023071502INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Depósito de ventas\",\n"
            			+ "        \"fecha\": \"2023-07-28T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"8500.75\",\n"
            			+ "        \"saldo\": \"173404.56\",\n"
            			+ "        \"referencia\": \"2023072801\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-28T14:10:20-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-28T14:10:21-05:00\",\n"
            			+ "        \"emisor\": \"CLIENTE ABC\",\n"
            			+ "        \"cuentaOrdenante\": \"112233445566778899\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE ABC\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023072801INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de servicios\",\n"
            			+ "        \"fecha\": \"2023-07-05T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"1200.25\",\n"
            			+ "        \"saldo\": \"166204.31\",\n"
            			+ "        \"referencia\": \"2023070501\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-05T12:45:30-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-05T12:45:30-05:00\",\n"
            			+ "        \"emisor\": \"SERVICIOS ABC\",\n"
            			+ "        \"cuentaOrdenante\": \"777788889999000011\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023070501INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de impuestos\",\n"
            			+ "        \"fecha\": \"2023-07-10T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"3500\",\n"
            			+ "        \"saldo\": \"162704.31\",\n"
            			+ "        \"referencia\": \"2023071001\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-10T09:20:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-10T09:20:00-05:00\",\n"
            			+ "        \"emisor\": \"GOBIERNO\",\n"
            			+ "        \"cuentaOrdenante\": \"333322221111444455\",\n"
            			+ "        \"nombreOrdenante\": \"EMPRESA XYZ\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023071001INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Retiro de efectivo\",\n"
            			+ "        \"fecha\": \"2023-07-12T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"-2000\",\n"
            			+ "        \"saldo\": \"160704.31\",\n"
            			+ "        \"referencia\": \"2023071201\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-12T13:55:10-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-12T13:55:11-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"448877112233556677\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"CLIENTE XYZ\",\n"
            			+ "        \"cuentaBeneficiario\": \"014180605605294205\",\n"
            			+ "        \"nombreBeneficiario\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"claveRastreo\": \"2023071201INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Retiro\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Transferencia de fondos\",\n"
            			+ "        \"fecha\": \"2023-07-22T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"-5000.50\",\n"
            			+ "        \"saldo\": \"155703.81\",\n"
            			+ "        \"referencia\": \"2023072201\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-22T11:30:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-22T11:30:00-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"448877112233556677\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"EMPRESA ABC\",\n"
            			+ "        \"cuentaBeneficiario\": \"112233445566778899\",\n"
            			+ "        \"nombreBeneficiario\": \"EMPRESA ABC\",\n"
            			+ "        \"claveRastreo\": \"2023072201INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de factura\",\n"
            			+ "        \"fecha\": \"2023-07-18T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"350.75\",\n"
            			+ "        \"saldo\": \"155353.06\",\n"
            			+ "        \"referencia\": \"2023071801\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-18T09:15:20-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-18T09:15:20-05:00\",\n"
            			+ "        \"emisor\": \"EMPRESA XYZ\",\n"
            			+ "        \"cuentaOrdenante\": \"998877665544332211\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE 2\",\n"
            			+ "        \"receptor\": \"PROVEEDOR ABC\",\n"
            			+ "        \"cuentaBeneficiario\": \"556677889900112233\",\n"
            			+ "        \"nombreBeneficiario\": \"PROVEEDOR ABC\",\n"
            			+ "        \"claveRastreo\": \"2023071801INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      }\n"
            			+ "    ]\n"
            			+ "  }\n"
            			+ "}")
                        .build();
                 
            }else if(cuenta.equals("3")){
            	return Response.ok("{\n"
            			+ "  \"transactionID\": \"32a4499a-f0a4-4e00-9435-fbce7f933003\",\n"
            			+ "  \"httpStatus\": 500,\n"
            			+ "  \"timestamp\": \"2023-07-28T15:46:50.802209200\",\n"
            			+ "  \"message\": \"Se requiere el encabezado de autorización\",\n"
                		+ "  \"token\": \"" + authorizationHeader + "\"," 
            			+ "  \"data\": null\n"
            			+ "}").build(); 	
            }else {
            	return Response.ok("{\n"
            			+ "  \"transactionID\": \"57a318d4-1b23-41fa-baac-c01630ba2849\",\n"
            			+ "  \"httpStatus\": 200,\n"
            			+ "  \"timestamp\": \"2023-07-28T15:26:47.885759\",\n"
            			+ "  \"message\": \"Microservice working fine\",\n"
                		+ "  \"token\": \"" + authorizationHeader + "\","  
            			+ "  \"data\": {\n"
            			+ "    \"movimientos\": [\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"PAGO 4 JUAN JOSE AGUILAR\",\n"
            			+ "        \"fecha\": \"2023-06-01T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"2396.94\",\n"
            			+ "        \"saldo\": \"177370.85\",\n"
            			+ "        \"referencia\": \"7528300\",\n"
            			+ "        \"fechaAceptacion\": \"2023-06-01T00:31:03-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-06-01T00:31:04-05:00\",\n"
            			+ "        \"emisor\": \"SANTANDER\",\n"
            			+ "        \"cuentaOrdenante\": \"014180605605294205\",\n"
            			+ "        \"nombreOrdenante\": \"JUANJOSEAGUILARRIVERA\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023060140014TRAP0000431254700\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"pago prestamo \",\n"
            			+ "        \"fecha\": \"2023-05-31T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"1300\",\n"
            			+ "        \"saldo\": \"163404.31\",\n"
            			+ "        \"referencia\": \"4092351\",\n"
            			+ "        \"fechaAceptacion\": \"2023-05-31T15:46:45-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-05-31T15:46:45-05:00\",\n"
            			+ "        \"emisor\": \"STP\",\n"
            			+ "        \"cuentaOrdenante\": \"646013206858315561\",\n"
            			+ "        \"nombreOrdenante\": \"JORGEALEJANDROGOMORACARMONA\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"CPO58796137714\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Compra de equipo de oficina\",\n"
            			+ "        \"fecha\": \"2023-07-20T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"5000\",\n"
            			+ "        \"saldo\": \"172404.31\",\n"
            			+ "        \"referencia\": \"2023072001\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-20T10:15:30-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-20T10:15:30-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"348612987530912456\",\n"
            			+ "        \"nombreOrdenante\": \"EMPRESA ABC\",\n"
            			+ "        \"receptor\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"cuentaBeneficiario\": \"014180605605294205\",\n"
            			+ "        \"nombreBeneficiario\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"claveRastreo\": \"2023072001INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de nómina\",\n"
            			+ "        \"fecha\": \"2023-07-15T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"7500.50\",\n"
            			+ "        \"saldo\": \"164903.81\",\n"
            			+ "        \"referencia\": \"2023071502\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-15T08:30:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-15T08:30:00-05:00\",\n"
            			+ "        \"emisor\": \"EMPRESA XYZ\",\n"
            			+ "        \"cuentaOrdenante\": \"998877665544332211\",\n"
            			+ "        \"nombreOrdenante\": \"EMPLEADO 1\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023071502INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Depósito de ventas\",\n"
            			+ "        \"fecha\": \"2023-07-28T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"8500.75\",\n"
            			+ "        \"saldo\": \"173404.56\",\n"
            			+ "        \"referencia\": \"2023072801\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-28T14:10:20-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-28T14:10:21-05:00\",\n"
            			+ "        \"emisor\": \"CLIENTE ABC\",\n"
            			+ "        \"cuentaOrdenante\": \"112233445566778899\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE ABC\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023072801INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de servicios\",\n"
            			+ "        \"fecha\": \"2023-07-05T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"1200.25\",\n"
            			+ "        \"saldo\": \"166204.31\",\n"
            			+ "        \"referencia\": \"2023070501\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-05T12:45:30-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-05T12:45:30-05:00\",\n"
            			+ "        \"emisor\": \"SERVICIOS ABC\",\n"
            			+ "        \"cuentaOrdenante\": \"777788889999000011\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023070501INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de impuestos\",\n"
            			+ "        \"fecha\": \"2023-07-10T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"3500\",\n"
            			+ "        \"saldo\": \"162704.31\",\n"
            			+ "        \"referencia\": \"2023071001\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-10T09:20:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-10T09:20:00-05:00\",\n"
            			+ "        \"emisor\": \"GOBIERNO\",\n"
            			+ "        \"cuentaOrdenante\": \"333322221111444455\",\n"
            			+ "        \"nombreOrdenante\": \"EMPRESA XYZ\",\n"
            			+ "        \"receptor\": \"BANCO INVEX, S.A., Institucion de Banca Multiple, Invex Grupo Financiero\",\n"
            			+ "        \"cuentaBeneficiario\": \"00101003699\",\n"
            			+ "        \"nombreBeneficiario\": \"PYMES CAPITAL, INC\",\n"
            			+ "        \"claveRastreo\": \"2023071001INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Retiro de efectivo\",\n"
            			+ "        \"fecha\": \"2023-07-12T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"-2000\",\n"
            			+ "        \"saldo\": \"160704.31\",\n"
            			+ "        \"referencia\": \"2023071201\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-12T13:55:10-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-12T13:55:11-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"448877112233556677\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"CLIENTE XYZ\",\n"
            			+ "        \"cuentaBeneficiario\": \"014180605605294205\",\n"
            			+ "        \"nombreBeneficiario\": \"JUAN JOSE AGUILAR\",\n"
            			+ "        \"claveRastreo\": \"2023071201INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Retiro\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Transferencia de fondos\",\n"
            			+ "        \"fecha\": \"2023-07-22T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"-5000.50\",\n"
            			+ "        \"saldo\": \"155703.81\",\n"
            			+ "        \"referencia\": \"2023072201\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-22T11:30:00-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-22T11:30:00-05:00\",\n"
            			+ "        \"emisor\": \"BANCO INVEX, S.A.\",\n"
            			+ "        \"cuentaOrdenante\": \"448877112233556677\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE XYZ\",\n"
            			+ "        \"receptor\": \"EMPRESA ABC\",\n"
            			+ "        \"cuentaBeneficiario\": \"112233445566778899\",\n"
            			+ "        \"nombreBeneficiario\": \"EMPRESA ABC\",\n"
            			+ "        \"claveRastreo\": \"2023072201INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Transferencia\"\n"
            			+ "      },\n"
            			+ "      {\n"
            			+ "        \"concepto\": \"Pago de factura\",\n"
            			+ "        \"fecha\": \"2023-07-18T00:00:00-05:00\",\n"
            			+ "        \"movimiento\": \"350.75\",\n"
            			+ "        \"saldo\": \"155353.06\",\n"
            			+ "        \"referencia\": \"2023071801\",\n"
            			+ "        \"fechaAceptacion\": \"2023-07-18T09:15:20-05:00\",\n"
            			+ "        \"fechaLiquidacion\": \"2023-07-18T09:15:20-05:00\",\n"
            			+ "        \"emisor\": \"EMPRESA XYZ\",\n"
            			+ "        \"cuentaOrdenante\": \"998877665544332211\",\n"
            			+ "        \"nombreOrdenante\": \"CLIENTE 2\",\n"
            			+ "        \"receptor\": \"PROVEEDOR ABC\",\n"
            			+ "        \"cuentaBeneficiario\": \"556677889900112233\",\n"
            			+ "        \"nombreBeneficiario\": \"PROVEEDOR ABC\",\n"
            			+ "        \"claveRastreo\": \"2023071801INVEX\",\n"
            			+ "        \"tipoOperacion\": \"Deposito\"\n"
            			+ "      }\n"
            			+ "    ]\n"
            			+ "  }\n"
            			+ "}")
                        .build();
            }
           

        } catch (Exception e) {
            LOG.severe("Error al consultar la informacion del cliente: " + e.getMessage());
            e.printStackTrace();
            return Response.status(Response.Status.BAD_REQUEST).entity("Error al consultar la información del cliente: "+e.getMessage()).build();
        }
    }

}
